[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
fs_permissions = [{ access = "read", path = "../data" }, { access = "read-write", path = "../deployments" }]

[fuzz]
runs = 256

[invariant]
runs = 64
depth = 64
fail_on_revert = false

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
monad = "https://rpc.monad.xyz"

[lint]
lint_on_build = false
