// Copies contract ABIs from Foundry artifacts into src/abi.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "contracts", "out");
const contracts = {
  kmarkEngineAbi: "KMarkEngine.sol/KMarkEngine.json",
  k2xPoolAbi: "K2XPool.sol/K2XPool.json",
  k2xTokenAbi: "K2XToken.sol/K2XToken.json",
  mockAusdAbi: "MockAUSD.sol/MockAUSD.json",
};

let src = "// Generated by scripts/sync-abi.mjs from contracts/out. Do not edit.\n";
for (const [name, file] of Object.entries(contracts)) {
  const { abi } = JSON.parse(readFileSync(join(out, file), "utf8"));
  src += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(join(here, "..", "src", "abi.ts"), src);
console.log("wrote relayer/src/abi.ts");
